# Generated by Django 4.1.5 on 2023-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('Inscricao_Imobiliaria', models.CharField(max_length=11)),
                ('UTM_X', models.DecimalField(decimal_places=2, max_digits=11)),
                ('UTM_Y', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Regiao Urbana', models.CharField(max_length=30)),
                ('Bairro', models.CharField(max_length=120)),
                ('Parcelamento', models.CharField(max_length=5)),
                ('Quadra', models.CharField(max_length=5)),
                ('Lote', models.CharField(max_length=5)),
                ('logradouro_imovel', models.CharField(max_length=120, verbose_name='Logradouro_imovel')),
                ('Observacao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
