# Generated by Django 4.1.5 on 2023-01-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('insc_imob', models.CharField(max_length=11, verbose_name='Inscricao')),
                ('utm_x', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='UTM_X')),
                ('utm_y', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='UTM_Y')),
                ('reg_urbana', models.CharField(max_length=50, verbose_name='Região Urbana')),
                ('bairro_imovel', models.CharField(max_length=100, verbose_name='Bairro')),
                ('parcelamento_imovel', models.CharField(max_length=5, verbose_name='Parcelamento')),
                ('quadra_imovel', models.CharField(max_length=5, verbose_name='Quadra')),
                ('lote_imovel', models.CharField(max_length=3, verbose_name='Lote')),
                ('logradouro_imovel', models.CharField(max_length=120, verbose_name='Inscricao')),
                ('obs_imovel', models.TextField(verbose_name='Observacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
