# Generated by Django 4.1.5 on 2023-01-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='utm_x',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='UTM_X'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='utm_y',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='UTM_Y'),
        ),
    ]
