# Generated by Django 4.1.5 on 2023-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastro_utm_x_cadastro_utm_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='reg_urbana',
            field=models.CharField(max_length=50, null=True, verbose_name='Região Urbana'),
        ),
    ]
