# Generated by Django 4.1.5 on 2023-01-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cadastro_cpf_ocupante_cadastro_nome_ocupante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf_ocupante',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF Ocupante'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='rg_ocupante',
            field=models.CharField(max_length=20, null=True, verbose_name='RG Ocupante'),
        ),
    ]
