# Generated by Django 4.1.5 on 2023-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cadastro_cpf_ocupante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='data_auto',
            field=models.DateTimeField(null=True, verbose_name='Data Auto'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='data_notif',
            field=models.DateTimeField(null=True, verbose_name='Data Notificação'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='num_auto',
            field=models.CharField(max_length=6, null=True, verbose_name='Número Auto'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='num_notif',
            field=models.CharField(max_length=6, null=True, verbose_name='Número Notificação'),
        ),
    ]
