# Generated by Django 4.1.5 on 2023-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cadastro_data_auto_cadastro_data_notif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='num_cnpj',
            field=models.CharField(max_length=40, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='num_processo',
            field=models.CharField(max_length=30, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='obs_documentacao',
            field=models.TextField(null=True, verbose_name='Logradouro'),
        ),
    ]
