# Generated by Django 4.1.5 on 2023-01-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cadastro_num_cnpj_cadastro_num_processo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='RadioReincidente',
            field=models.CharField(choices=[('Sim', True), ('Não', False)], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='num_cnpj',
            field=models.CharField(max_length=40, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='num_processo',
            field=models.CharField(max_length=30, null=True, verbose_name='Número Processo'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='obs_documentacao',
            field=models.TextField(null=True, verbose_name='Observação'),
        ),
    ]
