# Generated by Django 4.1.5 on 2023-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cadastro_radioreincidente_alter_cadastro_num_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='RadioReincidente',
            field=models.CharField(choices=[('Sim', True), ('Não', False)], max_length=10, null=True, verbose_name='Reincidente'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_auto',
            field=models.DateField(blank=True, null=True, verbose_name='Data Auto'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='data_notif',
            field=models.DateField(blank=True, null=True, verbose_name='Data Notificação'),
        ),
    ]
