# Generated by Django 4.1.5 on 2023-01-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cadastro_radioreincidente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='RadioReincidente',
            field=models.CharField(choices=[('SIM', True), ('NAO', False)], max_length=10, null=True, verbose_name='Reincidente'),
        ),
    ]
